project:
  type: website
  execute-dir: project
  render:
    - index.qmd

website:
  title: "ASD Rare Variant Annotation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home

knitr:
  opts_chunk:
   max.print: 1000

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    df-print: paged

execute:
  cache: true
#  freeze: auto
